
plugins:
- jekyll-sitemap
- jekyll-paginate-v2

excerpt_separator: "<!-- more -->"

baseurl: /silexlabs.org
url: http://localhost:4000

permalink: "/:title:"

pagination:
  enabled: true
  debug: true
  per_page: 10
  permalink: '/page/:num/'
  # title: ':title - page :num'
  #locale: 'fr' 
  #category: 'posts'

exclude:
  - admin 
