paginate: 10
paginate_path: '/:num'
plugins:
  - jekyll-sitemap
  - jekyll-paginate
excerpt_separator: <!-- more -->
baseurl: /silexlabs.org
url: https://lexoyo.me
permalink: '/:title:'
defaults:
  - scope:
      path: ''
    values:
      date: 12 aout 2015
