plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
excerpt_separator: <!-- more -->
baseurl: /silexlabs.org
url: 'https://lexoyo.me'
permalink: '/:title:'
pagination:
  enabled: true
  debug: true
  per_page: 10
  permalink: '/page/:num/'

# this breaks the build, cf https://jekyllrb.com/docs/troubleshooting/
# exclude:
#  - admin 

# this fixes an issue in forestry preview server
repository: lexoyo/silexlabs.org
